---
language: go

go:
  - '1.8'
  - '1.9'
  - '1.10'
  - master

before_install:
  - mkdir -p $HOME/gopath/src/gopkg.in/hockeypuck/conflux.v2/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/gopkg.in/hockeypuck/conflux.v2/

script:
  - go vet -v ./...
  - go test -v ./...

matrix:
  fast_finish: true
  allow_failures:
    - go: master
